# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-03 03:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_auto_20170303_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='list_l',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='lists.List'),
        ),
    ]
